services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        PROJECT_NAME: api
        BUILDPLATFORM: linux/amd64
    depends_on:
      - mongodb
      - valkey
    volumes:
      - ./config.toml:/config.toml:rw
    restart: unless-stopped
    networks:
      - default
      - proxy
    labels:
      traefik.enable: true
      traefik.port: 4000
      traefik.http.routers.agin-class-api.rule: "Host(`class.agin.rocks`) && (PathPrefix(`/api`) || PathPrefix(`/socket.io`) || PathPrefix(`/apidoc`))"
      traefik.http.services.agin-class-api.loadbalancer.server.port: 4000
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - default
      - proxy
    labels:
      traefik.enable: true
      traefik.port: 3000
      traefik.http.services.agin-class-web.loadbalancer.server.port: "3000"
      traefik.http.routers.agin-class-web.rule: "Host(`class.agin.rocks`)"
  # mongodb:
  #   image: mongodb/mongodb-community-server:7.0-ubi8
  #   volumes:
  #     - type: bind
  #       source: ./data/mongodb
  #       target: /data/db
  #   ports:
  #     - :27017
  #   restart: unless-stopped
  #   user: 1000:1000
  #   networks:
  #     - default
  valkey:
    image: valkey/valkey:latest
    restart: unless-stopped
    ports:
      - :6379
    volumes:
      - ./data/valkey:/data
    networks:
      - default
networks:
  proxy:
    name: proxy-network
    external: true
  default:
