[general]
listen_address = [
    "0.0.0.0:4000",
    "[::]:4000",
]
public_url = "http://localhost:3010/"

[oidc]
issuer = "https://example.com"
client_id = "client_id"
client_secret = "client_secret"

[redis]
connection_string = "redis://valkey:6379"

[sea_orm]
connection_string = "postgres://db:db@postgres/agin-class-manager"
