[general]
listen_address = [
    "0.0.0.0:4000",
    "[::]:4000",
]
public_url = "http://localhost:3010/"

[oidc]
issuer = "https://auth.agin.rocks/application/o/agin-class-manager/"
client_id = "ct6w1iY0kI6vMWUVymQF6tcnui0xlyo3gMwR39fa"
client_secret = "URF9xDXqiDiFYBRLr2pXUglhX0lMt6NQuuRhgRtL4hcyX4lg5uH7jTzjxgyrm2hS1RriH5wwxQkW6oUuvXlMxBNhGPKLW6NUB966FkVZqqIScU8cUOKVsR2ikSevgDoV"

[redis]
connection_string = "redis://valkey:6379"

[sea_orm]
connection_string = "postgres://db:db@localhost/agin-class-manager"
